### ISSUE TITLE
Hey nate

### ISSUE THREAD

**Issue by nikolaswise** [ungoldman/contact#3]
sup

**Comment by ungoldman** [comment]
Watching Bob's Burgers

**Comment by ungoldman** [comment]
Hey @nikolaswise, you and @paulcpederson should come over to my place to try some of that bottle of whiskey soon. I bet it is good.

**Comment by paulcpederson** [comment]
Into it. Maybe next Thursday?

:beers:

**Comment by ungoldman** [comment]
Works for me :cocktail:

**Comment by paulcpederson** [comment]
You should assign this to @nikolaswise

**Comment by ungoldman** [comment]
@paulcpederson I think I can only assign it to people who are collaborators on this repo. Good idea though.

**Comment by nikolaswise** [comment]
🍹 @ngoldman @paulcpederson I am in for a next thusday deal, that would be pleasant.

**Comment by nikolaswise** [comment]
How about at like .... 2? Not like we're busy.

🕑

**Comment by ungoldman** [comment]
Works for me :tropical_drink:

**Comment by ungoldman** [comment]
just confirming, that's thursday as in today, not next week, right?

**Comment by paulcpederson** [comment]
Next week was what I had imagined, but if today works better, we could probably do that. @nikolaswise what were you thinking?

**Comment by ungoldman** [comment]
can do next week too, just had interpreted it as this week -- whatever works

**Comment by nikolaswise** [comment]
@paulcpederson @ngoldman Lets do it today - why not. It's been quite the week.

2 still work?

**Comment by ungoldman** [comment]
2 still work. See you in a bit. You remember where I live @nikolaswise?

**Comment by nikolaswise** [comment]
Yup.
