### ISSUE TITLE
ArcGIS API for JS does not want to render a layer created from a FeatureServer

### ISSUE THREAD

**Issue by kudko** [ungoldman/contact#5]
Hi:

I don't know whether it's a bug, but I cannot make rendering of a featureLayer made from a FeatureServer, which is provided by Koop, work. 
In the readme file it says that Koop works with ArcGIS JS API. I was using the example you provided on the demo page: http://koop.dc.esri.com/github/chelm/grunt-geo/forks/FeatureServer/0.

Is there's a chance I am doing something wrong or is this a bug (may be it is not supposed to work this way)?

Thank you in advance for your answer.

**Comment by ungoldman** [comment]
Hi @ievgeniiK. This sounds like a koop issue. I'm copy it over to the koop issue tracker at https://github.com/koopjs/koop/issues/263.
