### ISSUE TITLE
hi friend

### ISSUE THREAD

**Issue by jgravois** [ungoldman/contact#6]
-----BEGIN PGP MESSAGE-----
Comment: GPGTools - https://gpgtools.org

hQIMA2DX8Pw201lnAQ/+JHVUaa/5oThYln5hdY3jh9Mt5nYORD/ZSCIM0LTlnE81
jJBFC+nlhccTs1HVCx3JY8RgqrWnUB6oTaQ39WgVxERaVWhI4dES7AJrOstyYoqc
30SM5FHj52dFepHVsfVUXvbFR1d/avSnATpG0zz6WMcTOSh0hFKVlKH+8mHTkIar
2nD23datShk+AkE9B+vQ0bswng92DkOYBN9m/bTUYHV3njNm2vHuCqzkhyfwjueU
rX86SHn9abqWHq4zcTZtgVkN3s2EPx8uLsPUNltfi81+/yKgBYYe5mbQ4+0DGoPB
BpXF4h5Wpod8JwgZevebLDT+bvAv0VDtmIoUbA/Nt9Y4FeAQ2WN/Ul+wcU720+Ko
yPR78s1y55KeNT/g3cMTyhUDhQVeqWJopxmVl1ZQt1yhAxplxFRoV93NwlEELhFn
b0u6Ae/lqueMSzDkGea/L+BAGYqpFlNvz2xdS1UKh5kk4doy2IaiRPy/4xxBC/G7
bribE/pjzYsn9YPxMLHDB/GCq6yvyfNNwWv45M3h0QJxmwx4HHX7GC3DFhvEIR1C
0jECZTU11JzSXLpDRQ0NWYq5b3mS4lt1vuvkCHWSqTyQ9HUJuCRw2loR+mebCSeo
CcXmcw239m6u/9LX0Mb4WomqegBsvrLkmTfB3Ur4Z7KPiHnoGMvsMe/qBdKsx5OF
AQwD75sz7YxNsNQBCACq3y57jGZxEfgzdKPKfc7UtS/D/wPg8BvgKRNH6lVcTSm6
+QsoPKc4YKVMTp95b3HWfj/7jNrSEOMn0/PCS2uD2vE1LlXD5YaVtW+CdJ4dO3MS
afFOZBLTB14rSJaWfPgc0VqBUBSaarZUFxq3ndd98th9PvaK5Vn7fYjlwDYB/IcG
G3H4FAyd+6ZC/PTV+PiohggRrHu1fFBwe/bwKr+FCSoivzJpsXYv3Kr+3l3EHN7w
EtzoWYma8ThUWKu/OJPRxDRXzA+zbw9DCZy0GfCkGkTve9+GlIac71D1cOrZGY6Q
jhEabU96w9fuKrFjxf9wzG8Zolq9kQi2plNMAR8e0sChAdaqTbizuVAucyeoRgLa
EggfpxGX6shJmYPbO1KkFBf7oW+ZlfCqoaZxW3XeTYG1ftrxVEuomXbXuyL9toMS
CEpSDi/ZQuBzvpvfDWj9C+OBxpiNpSOlgjNh1hLjxEceROuSnp3bvjj1CYUZIAgy
5BzvOGLzrQj5ROZQYSYAnQDD1OlF76AbVI4nyDzaZepIDutmWFWAfYBhBV8Gep9P
XsHLaBk5Rpkk7sxzpcDtUlxRmOwujOw3GnJbXB0uo9QDV27KwhkK3mkQKkmUy95L
Y+vqgRjNcs+7Ra3uU0oan5QidwPu9MMOXz1mc+jaKXL/n+OuCxzPt4HueYAWzpBo
BFPJXT50/3bCH85N/1M2tQtK6rQxCC7JgzuNKqjWLUCvSPxXAabc5TSYnYCHIzMt
x6BoNdd9AYkE8cYhQfuVgbz1dLF9wnqaQxV+wU2DZsaGYWXd0bREDc/VvASHapgZ
7/s=
=VqLN
-----END PGP MESSAGE-----

**Comment by ungoldman** [comment]
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.47
Comment: https://keybase.io/crypto

wcBMA++bM+2MTbDUAQf6Ap5qJnDTuHkHOY2bjfgv6Z+vr7DQJmqn31LALKWtuZK/
C5x6PN8oTyAkq9zopgng9ahrFVEzBn6ahIRpujDRm9MlUVLFv4CHMwLA/WWrhtJw
oReR14GqZT0YYcumWqEoTAfxvGNMPr2SInnC+vYbQXl9yQNhHtPcSxwUD5PtAd4m
LM8T5vAD/P97HKTECzoScJi12h/jyC57jZU3UlE3Hc4bR8bVRDgi0+JC0xjqkrIV
WGj6y4zwICTepxAeGzSrhfe+gZIvZdj8+41xrk8tRXf1aB1rl1OYo/M/+75YQuOD
hc3qEfIL2Vtii7ruzYv0lhAyq9gYEJIYzKsdYgXam8HBTANg1/D8NtNZZwEP/Rst
srsSp15jH5Dn99jb5ZpJahJTAnup9KyEVQ11lUvDCuZDxU/hJkfzsSq9H/hGIZbE
lxiK6rOqiHIspbtY0RBaLmReRGmGEfUtaHRqqkd8gH30ESM5b7Dqr0ghPmoDaoYg
PCZNChWUHE+OCntxUU6xY6PUTtW9RbO1sB58ur077UxjLhS5f9jUdbFh/16N9mS1
L1Utg/PXhbO79pvXai9V7CS2VHvX3gp8UIQhQN7nqyBiO6OaAZ/0s4El623lfZki
Ogv24hJrf8UyWa6bKj1MjPnEFxTgwEWokr6OatYWZoxL3FL6KL5iUhPknAyJTnKQ
NKx/bz4SB7wf7BIf1tYsgE9SWeDTivZ1gWPlD6JsFGo78qw78brpsDDH1x7f5XyA
CvnZrHMxhoqjRDR/qYRIOfAs5OuATc8qxkOo3FmqATDKN8cpWNDhw11dUynS+dsy
xuSSVk07/NH3pUSIZuiEK5bX19NbLNsmtmh7L+JgIOj9R0VG03BtCVyjKjJVnM8Y
c4SzrXQ0Opl7fPDPwxKrMEqBiegomOr1mMiltUo2YjDPceYpXlRmtaR082p2KLiE
1h9fqbM2xu2aNwEMw5cbxFUaexSm63cAVWl4a6ZR/g/MCtbWCUTmIPFDRSIHznOp
IaNu82M8hVzSSIsZxpu6+GAEaX8brOSn6M98flM80sQOAaN9tUXv/vEAmwLf3HoQ
f+QgEH1NoLb6npUUYrjd01pBRfA2mg9jAiOczf4IV/fnQl0t1rW8Dieq1MCNNhMV
lCinR16nPkPcPleTGwHPfhSENTm8aEq+j2wp/lS0EwHxe2zD47dxUgWIayQ5f7Ut
g242Zx0qAlzFyXrqVvfW7DBrL7/82oNFHooSCC/4zI173zSSbNDenyBnPTMNBXah
93ILMkzVAxOG37S3lmVAWPEuQhUQxUg885PPeP5h5IFU2obF/oTf2w+rv6dmoJzO
wOjkjg8j+N5VPuhTJdM453z01BDrd/LpMrTny84dyNTzSSJ0R/sAjgucxL1PIf/K
MZ/L/36nRVp1a6Pn9ImazUP0VFtXxsk2qztAGRW4HFOmHgdGjc6QoFPGpm8Y3+Hv
VDEQezvYmvXv12bLjjRIJpNUEDBy5zkB2QJJdcv4BzMVruBDbIGJ1WFw3t/G3A/0
dbW3YoyHhEJ592pk0GDrB/rWlhsBpt1hkaPv5J1UL9g/7YzCFKMPyb1dDPEYfQ1/
mE0tnE1u/jCwmP2q5gMQb1TO/Q1vIVC2HvqpPqdI6I+JxFDMxauHBT5s6IBlcB2O
Ir4df9VCGJZQrnCpz+gylVT308GPk3mZFlVZO1e0qV2t+7W9mBRveDXknsoyF46K
06DNEFyYUJVDoOzJoUulh9v3qBo8inBI628/yjHpyR6HwUoYHqVVHrOSQmyoHaiv
A3Z/Mqks2aIYjzBRvNiPZcVsFrMPz9cyfYtatEn1UIryPUeIPAKY27bUL6mErP0x
FJvRBLnIAE3I2B+KF5hsxyz6zO9bTxZOBefuar/BWcUmj6ILVRwAIQfVaUnYob3C
27CLwjBjhF/YjU7/4MSDsUjhSUAUTFdqKyiuIi2kMkrp3e2S4TRphOA2QjkLygFX
WaJNJjCa4Lv//xMm+UGb0EZ2pU5/On9PKz3/dyMFnZKFBubOFYygyGxHcmCvKpHk
k8tc4osYkkvrdVO0QLCSK9hu+G6H5jqF3xzfh+tYjjvCoDU4V46mFovAyY0aRsUD
t1Zgk9BuL1WweZiWx7LYxZC29ob/ALdAbO2K9/miD4Jlsp2uNCtNveFVic9UqKIO
/yzJoFVlVvQY6CSKfcvc9aPuqJ6REsCsXuY11BzHTuUfLpslIhd8LZKcfi4bDx7B
eK4m2R2LiYti+Z8CpU/JV0GgNTXFqTkuyTyDRYektLGS9vokpA99bkA/bO56cEM6
6ip3tCzR5g802BWlCfHBIyhZf9X/ZsY22n3oExedqRnxuIPtZe2TFsuxx65NQMlf
ythvD1a1dxIOr65sQF9MqI8X9m8WnHHy1XxGi1tqwOdEPw4MgvJp6JDXVIhVHYpo
OYB8xc6QFDRiMCTdaP6SH6bOM0nF1KByhZFpcFcmPj62i2IFn7/YUKKtnjro5OUz
USN/63j2scbcyn4eFMXc7jFyef88j4XEa1SURcCKD0TtID/n2u0vnQmWXDgnG96j
s5OcltcyHI8SNiRBYY08et8QOhof+XGC0BqnIyjR26k5JnhX4jMsoioMvdhcfsd/
lhiIZwWZDKmNfzfyGjU2z1edZ8hkoULU+PMCBbLtxp/63241fLmRmPIAKCq8u+Ih
vGqAa2CggtPBlxklJPdr
=eRO6
-----END PGP MESSAGE-----

**Comment by jgravois** [comment]
-----BEGIN PGP MESSAGE-----
Comment: GPGTools - https://gpgtools.org

hQIMA2DX8Pw201lnAQ//Sv0Z31aftbK/N0X9EvV0wleA58UtclfFOfIMAYv0LhhR
9RwBsOP11+XuRu6khkKqN2yrcSzss7oJPqLVq7sr7eCMkBxPjM1e2P+ID1JC8Zdy
JJhUjUdi9MFIeplCU7ipgU3Tr1ghC1omZ/xPzacDZ8q+tInmW8fhrVowlU74GoVi
EJW5bXrULjSOVJzxNAAXbxSbrIKZVU/R+s4x/On8eJwI4gtyfIi9iflswryCEnbv
C04Rq03WrDPYCxlESOcE74LVraY1gl0aVnfB/HnkUanLoy00ZKlVpIedGgC68HQz
UAJz96D3sHJm3vcwolPw8CceZFEllp+lR3g1EdoGeZqN6XV41ZNtvf46khaoJpko
o3k4ECvRRkdfshZ9ac2fqEBcNTu9Mbmc17dcAX9PkToOMVZFmgMAB1qAxeSiCV8k
2dqO0Xs/cKSp3MekNnh0Y6KDuqBYnUu9/FwyPAsGP8tH8hhU8CCaqMOXVU/c7CXa
noq2PfCPzWPPfVBFSM9rqPfFZOSMZXcwTh93L7pTaiHuRzr3TDbsfhN1jtUEzAvE
h9qlgwHhnafKcI2UQRmDkRPklZh7HERM4FOZhIqTGLlxxhg2aT/YN/kSdRw1HsCR
sj7nvPHWaH712bA78lwUcQShEDplI5GvK/hjThEThmCcmKG20V2I0Mp62nVdhDHS
wPsBMDvtUZypLAdklzxUrwAVOOJCosu4SAkmF/jhkL1E2eOZAghXzu0cgos/pvoz
Vna0DSOImfKl2KsAMSFc42CgF3sEM99s7O030liyleCiR9eOWh97JSuDE0UM7C4o
j5A3jKmF5E6yo6tYDyafhYZDgp67t96ljir39AATWfWHsO87DmQAfWt0cmWIql9i
9ozCR48m1dFAmO4+C6ieyTXzl6Z9+MYwFRUR3iPuL+4LxjmWr8sQ77DhM8olqgXA
Au8dyd8Hlnb4P+3Q5pkB3r2E5S1ohJW4cXXb5X4qI8lYgMxqF6mhgVk8NP02gYLq
HyfRFHTXI7mdYuzy/T1/mrsxLkFrqcNLM8WXeyL3GvK732AnXjD1IqS9mTfF1K9k
i4TTU82EwfGf2G+he1KKDs90FeK6rg6TrZorxMs3Nf725GQNDE37/iiRJsh8e/xX
+CjtSMIXfFI0npGMX2c19w/YIzpq3PfQwNr6/TGxAz0108QHZbYq3GT1TT1qbSXJ
EqPZ7OT61EdbHkkbv+rplZPdV6I+/c8wSBvn40nKs5pn11xPQvDthFgkJXPiPMX6
qRGLY6RI8I8U33i3pQ==
=h3jF
-----END PGP MESSAGE-----

**Comment by ungoldman** [comment]
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.47
Comment: https://keybase.io/crypto

wcBMA++bM+2MTbDUAQf5ASOxnx3xk0zYdrwwP+Gf9rmwsyqEJ4OucxJ0gW25dK2J
ma6BD65fa21IpazbZssL6o8kM21yFNT7XjZmeMAxTa42OkzgdCvCsvarKRy3tnA2
3u5VjrYunXokPZs/qSstnwX1y8dfkmqPB/51ZRnu/DvGUGd00DU0Ko2xlPctYK7U
OIWP/xnDfqOUOmHJdz9V3hEsbH1m94Lqn3VUNIiGAfgy5nkEX0RUkYzn1Q/SH9E0
BhY8v3x0onv97xUlTkCxhINXa02jqSCKHF44yqNkYFVIYdoY2f4gRKubtYRPzfL1
zvUCb7pUBO1fSIOt9TpvJsAUzdndLEMfrXz7dycz3sHBTANg1/D8NtNZZwEP/3Zl
QcFRIPZHSlTfz+oAqJJ6i82iJAC7iGoFFPIRDgkH/baTHzJK401ZvdHRtEL5C5AR
RMsEl05UdunyE1m1MgisREupAj0mMLTe2+1GrKZc2gPhsWgSLK+Z+NKRXJN5Ud/J
Q3jABPvOLi9+XFpdVVzXvg8l16UCkRxm/8OtQBjYnJuzoEZd5GuFsIqdo1+Hv27E
lpbjkiGMjXKFoJa0s+411uyQc9y7wwSyYVsTunryqKcn080/EDeehN+4f44mCub2
e4CFB5mXRpHvCCBozRraCAG3O9Lf483uv3Y7GehttTTn0iqjOxlvlaErWdRUO4Hr
BuVjkrKe9BZEUPmAsUr7Z8MM908fDFam/lxZ00QBmlNvWUHAvAmJq1xZz/Cgzxl2
iqtHp6/qFjd+DAlEC0aS7MxQcnzZMZM0EppELSJevDNfY3KE2fJGJZiN83a0fKVy
xVrpuLH5a64zw7+dAl4BgR0bfB3aCE4WyXt7LZuk1wf+AAltZg3pcz/w9BTDkStH
2r4Ao1DlmRJahGQk6mwl2cXli6V/EESl5XSVEMDR97QTbJvZhO41xGWr+cQ1wBNd
9rvTQZQQRGMEls4zAcbEDcnOH2whgE5LFg4PbXG3tMh1zRCBuVwyMzrrHL7PNomT
TrmpB2LvANArvkU98QVhRK4ImLVXwudOafgn/udG0sLfAZPmyvQojYWy5gfExrlX
oSas0bKrj8uU3pQAUoD5FcjyIGFNrviN1A8uSOWuRn/8jbOvxOZbhePkXywHVuob
YW+DHfyIGyZFBmLnY3Hn/XhcwVy2hzcgnlEvM+FTmQhVO0uJuNDR7RX12rKXOQ/G
Pi8IjYvRalz30+jDUGczbf/IInI+5Tq2nfs+kk5TWGLrGxnYHlxzhEFuOfyRLtd5
bWOdxr2Kkfh7hDnOPOdY5HY3/YfjpnxXfYcN4rRp53otlTQp48ym/LIKOoWkoQQD
OqWzNi6dU//NmoL2r8m0MQ6OlwIWD+FFGBfxRXz5THCpn4yWUpKjV4OXcqQXr+0X
dm4ceE8Rez+1WAFcCOg5jfQ+T/tmzf4FyH8OhiiBb15OUJHaBrsB3kJK2jg9Yofn
5g4QFfcOjF49emNDgzp8XCwC+RmtYgJ0hUvx/GsMFmIv/VGWyPaWnIl/MeYAWPs8
Qrxc1gQKA2aFI4m8FspuNwbJrDKuJeXHIivm5to6ua0KkAzKWEFEK0zIZH+fmHII
1/aP6WFCqHg1p93z4/1mVr60CtVTzZRSrT/XnV30GjngjwnTNeGNAm8hPaZcrcKi
vrCIyLsznWIvgpbm/TLOYElrcyxAUWwMBy51Emulj2HF+n3mu6l/bj27NO4nJef4
zEzJx5Y/hyzb6DI4kyW61PgyHhOy3K4QR5sdU5/5HFnItGJ0U6yIGpXmbzWvJW0E
DNY59MR8Rfxu5SqD6UizLpVkbpWrUmex1RYha0ug9iKyRuMvFnOY/t2rNJo4MfS0
8QxD9BCQqLxfsV0BJbnkhN8cxWeRobCoA2TUUWCI4hLDNdcwD+ZifgXsMzjDsdLb
egwAnQVhuCURI+47OB3gFVZJEvyx4RhjBJ87O/rKiNdaD6F0cpuH0HTtLvi2mKMd
ZHhtK2Pdcsgv6/eCfQLh2+xRFeR2nbUW6/JGOI2CeYy3kalvMA6+wZGtn+CQZCQX
NvwAWA7kxwGkrvee663bV+aeU8Ss9iLKyUU5WRHUzVe907fowZtouE+D3V7UHSjw
WdFcdRRkWcrKwu3Y/bKMRd4CFLjox2LlJJAsTVt4tjTF5w+rqiAYSPBmjqDo/DGn
isYsq2mPLR29xR+7U1jZDisMIhv0IOYq3NwO5zwaU4D+nVVKP5A1GwRCmAzBkkGB
LkZlqdmn828Qlw8VT+/cMcYZ5lcF4TbqACIRKREgljA+8ORmectVylwEgXFKFXCF
=HWAU
-----END PGP MESSAGE-----

**Comment by jgravois** [comment]
-----BEGIN PGP MESSAGE-----
Comment: GPGTools - https://gpgtools.org

hQIMA2DX8Pw201lnARAAhJPjAGv+liQ2gOUQkRa2NEFqU+ld2fLAkkgl5yMVGR1y
wwZ6O0tq9UJ0a0Gzuly8ZdUO61anFvbllu1wNlfvQodj3Ot5wgHKq0FLt3u+5+r+
nuEJPG1N+/R9eC3nObX7/KkXsjhkrDcOkezqQCjvMmZY4LJf9ToUyUPHSTdYMCFr
Ys8dZ3HH1lUAWew6C760hBDXnJ9/bikLHA+KNbI6F9qsWnHv+KopR99dJ/G+uF0r
ZF+vSugl9DszC35hIofWH6aVSKk9RNLgtbWJidRIg6j1fe/o9G3odSASblitKVH8
DUXZsVZPgVQBotGMc5a7M+/NCDS61VQdmqEO1PKOXabIG8xWB091AuF75+XsfsE4
zCrIvjZQp90CPMM8S0c13HG638EhL23NoIJlqF4fV09aLsqJhW6VG3BXLUYHRTyM
2IBV5rJA/dA0sHZc48Z1J6LpuO03fo2CcSmm+vQGaAmpKymLmKgmDxkHjI2k7jCx
CAES1tN9B4ZEi/ptuyuKqW5XrHO1xmiSOOhpnSFze9NoQS22IhNNc5e30FcGELDf
842FnXWf86wqAl0042hI7HV2jftokp3paPfJx6o5tvJKJqtybMI7On9y5mU8iGlG
dEoQ6SIbWIorffa0OmuqtNWDPHr231FYufUkdxQ2thhqoyvF1MFseXzfR6qJqv/S
wQ0BK8ArAyXIR9NLEmhfXCTJu9POruGpI9DG1C2A9Sofeq78VFCanXh2YPh77jOZ
6dRnQFnfo2T0ey1jA8KTamYNspAT/uIU03frCLxFdFCyI6Xz53hL6NRVwUuFmbdp
gJ9+Q8I0xqKd4S+rtU1U1fZrEcDo5VTdT9JCfeQd9wnDudukX1ZViCqR8cUW64me
pgCCLixt4yPYOvHRzgFzXjuZRo78m1CrstouznyWhHs1g+ylwA/c0mnQixG195BF
appJw7XT20owh/b3b+iItjnnvgmsGorYHqZpDD35lbIbyw06nCkmaZwZ2ctKy5wz
1O+d+kPRN5o7wB3Xbt1sTPQch4ERJ5pG45Dd/+HWaQloclvMV5V7F/CgiQ8266P7
QJISFnqGHQEeHAFrG3EnHiq/Y5m5l9q6k4c/TyGMl7LtIu90Fb0xeltMqUK6fn5o
+9K5hztXB8N/HJi87KhjnweHNkV6VXYUtnpOJ0w0E+o1oKd7tNHcw1F+GehFpvH5
F+OE1UOOMHHm22qy+ajkEEAreQs6KpQsJmnzEXzuuvXWmVa9xT6mGGf6DNNjKwTc
KtKE+Hkh0s7SATPxeM07XZl5oNHeVcZZArQEZxc+ng==
=R+gS
-----END PGP MESSAGE-----

**Comment by ungoldman** [comment]
-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.47
Comment: https://keybase.io/crypto

wcBMA++bM+2MTbDUAQgAnqov3fs/spkUTT5SxKfwSqfshCR8/Xt1MF/GHmw78fLU
s7ZuJsTWTKCRI2t2wyruDv5z2GOW+pgoDYU2xyH2v7/7cD6IIjlz8xkBET3idlYY
G1/Dc7lIrpE41HU81V1SLYQv5dMoHs3ZHUJYr6AMLAgKVFP+quFCNtw6jDLGt2dH
sdtLJWK5d4cfNAw4ommMTU1TY8grwWXUShJ8xGvlaLOSHQ4wO6O1uk/Hacyot04c
oJUtaD0WL4uHP4/UmkdnpQb+9w/Yx+NJTK1UfrkhVBs2JShbHL0FYRulTvmAoGRH
SxMQLtwpcEUdVpSJe7uq7q3WZsYyAE9Oy2VHrLdOKsHBTANg1/D8NtNZZwEQAKbF
qz15l9oE3mdgUURcUW/hH9Jx6wzTAbkE6WS1HHJ2I/35BpYTMiW4hYVSu6VSZAmq
LgwzupbQssDnxpIjcsZIjH+PP7xArnJzMujXcFNXfAiYpeztHG+lTGwlyPoUeuT4
u9h18Mrzenb66m8imkC+9gG/HP6z0X15PJWoln2EeEJ8RldDpSxRL4GIbYEvMfqg
VR4Lrlzrqm1Hmg82qQzN2QWBy4gzFpsNELH01N/VG/GLy0sbysZO0ueQ0/A6LyHq
k0D7mLASWTDkIYlsH4e/Ldk4LiMZeDK+1XP9ByYgS073PNEANL2w1eEBaejuALW5
BlP495TRzKrkBVIV9XT4hc0aHXlpp70tjuBUPGiB1z2BLlwwxHCRG5DDYsG9Uwjk
3QVDij2irADyCQuxhKlYNeZ0ZxHC1SEwH+ON3L6but8KZvtauEFyszIEwItjl8tN
9joVbkxD0XQbJne7/XUS8oD7ItzSIYiWPi32UcVhZttLTdNuJbHJjGQzFuGQUsoT
C3fxCrPZ5xsG48OqiAhxieibXCswhHqSw7VUz0TLjm0botJti+/DJ613Bwfa/EZO
VsvnpYnh/XS83SNJsho4WlFkkzG60l/kshS+DL40QW5MvRpIIrYLpRgccbUV38OF
ll79Cz6vZsbe4G6ka+2nfwyvRrMx9knRjIA1bCim0sXGAd/A7yxLWkvyP4LMOWOY
4HJFqT2pOpFmIdKYzRc6yuZPiayo4cEYDQ7lHjqYllc+fLbXAvFKTnIFG88Pe3PW
q+Ym0G1VownwKhfj+x3tC4a3hsYtnfnX8P8D0Yvs7a+TvgtYWjeh4jnq/b1gh6Jy
740k+oSLFRLQafp8myiLgTfWhHdYJBfqfOWNqen+vUDT5zPilH2mO6PLUqde1tak
Acqe6xSwflsvHEhUeZFqYM07wO0VgsLidFXjbxBxXnsO/yUmLf+q1vJNW423ZZA5
YTEHAIO53DzxfXqRcst7aV2e73tIGIRj3GvFMWmkCRh48j/HdqbkXmn2Ho5idyFu
pHyDipC9xwpc+25N8g8I0wa7XoNGUv7OZplZKFXNqWsI+aB4O+2/DlNde/FAJYZG
yAehQOVt5BkHo4ZHN1Koyn3yYdqhJOsr6PxkGVGzmG1rL6vpmrt1X/uy0uDk0HeN
wIJelsgJbgW8RBPNIEtb+WYNQHxeN6bhj4+vwbaRKa/7YnYHjQ7tm6oZ++5Jx37i
AvxBSo2Avqlbnk4CfbDOA0rgfgUEd5FAQHIq280U+iKvOaxx5K3ROV6fAEzV2D7a
KWrrvaNjP6V5u/WolKelZf1s/7XkwQA1H5PLAKR8of79JECAL2cMDG1ONz7+eMaG
RVcZJlbCS2NuUd0tzb4b94zXJf/WrU4HyOZfgqWVMjKq5qF9XBpTGLlePI7dQEO6
CMlnEPNXECV/Rf78gn/MJ8ASGpDvkSMu+5v5WMXtGbe73QglPOZ8msWTPW4elil1
8Aa/bfjUF2//tpsFstaktceb+c9HOzjYidb7yNRH3BECsJPVZlQcMEYy9MPbm5/X
/0y/yTXh03a4f145GBb0qF+PWxABgGYVqk+vc81qIpcvPZdIqhmgdh02MUKYbUHS
Hn4XcVgus3+LYpifrPU6VC7cC6w+ExUs39MKSmkhqdVnWcqZe2dfvJMSLKdIyHrx
jyoDJarruzx6WVMxSl1kTxEscm3An+uWKwYiJyTt4v9knuYl2pYRpl2pDd3pQWXX
XRLAZlXZpVM4SCSlR0ToMfHWmEcETShhYzhpfqPtlDVbnHJNtXF/ZKYEPD/fSbRi
b4serxmXIbbhgDpU4Fewffc9artMSm2NFZogUaIhHP6X4Gcojhpb+6KBvUz74qX6
MojPas7Viq9r1Zv/SZ0IIKb6iAutRYWVs9HYlFks9wsVcLJB5XfK0DEFnqjb7ja+
ES1dyAx1UezOcKaovyTNWKUvkTISJ7jadZX5NAAERnEyb4KZHt6dFM+2bzLJYZx5
5ekxyrAPOmTICM4MycdNV+i6rz807SWvhp/dAWKkrEAnIiG47kvFzBvvl6A5kyqa
cRngKEksYxy6jjSt/eHlVncBcf6EKNl2f0GvOgN8RKLpD8ZUnaLs0yg9ogv9ZeiU
Y/aiH9zm0nECMUS3dM/FnuxRzdapGGeNq4p0DbvQKoLwR+uJg6HPXhXM/rps8Dkq
k2SYmDlZ1kRCSCzXMGxewaKbX14Sy6BY/AbEWRUltecS9N1AkycmzAEeaa4faf4I
iMle5CWR0gRoXMxXv89/WsehzSs7bE8E8BYEltw31cyhWceOyWVjDrzjvkCJTA5P
6QaDCQZ+rc0DXGat6mwE0V6VKIttN7SAXbIvwSYsjIFMUQvEWakrPKlTlETLEztX
GuurU3Q0KioeDzcKHurW81s/BCfzyIonUY8PbTBIMAlpGOz5ad+o2E157vhnE8+Q
quSpepNYFO4G4R9O06QG0nE+sh/GpTZMUtt+L4PAx1+YWvgk/Z2TVN0m2K/MGHNC
8d60hyNEgOJoHUfspPOXrVLqkmcnZ0NzFrAYwhHYR3Fn/hhtnmR7w9lU0szqlWGi
nCOAvPxFo0w9R+n02CnXzK+X5UOydTdW9bwm2TEfXrVFHh04MPXSxVejeYih0D4O
x921nfCZZGClJZoS9vN1S57vcWHypKVKwfJsEfSLPDT0x4RqR0eTDu6nvVkRkKUs
drJ9dq7KYxlFYL/Abybp8mrwdQd1ZgRi0oCnUXj20y3TI04NGnJm1ECzWUvMLPtr
eDTdh93qcz+S0+4pqjCt6I2HGUlJg1ZtXZY6PLOqVAHiR2Bt9DRCtXspkIePpw3s
tu4pWMs17ETHnfVkAhNtEVFfy8iNaTePGZIrYCENwo6E3XGGD7q6cXxBtxt3WTrL
40BA7++jDOFflXzR3QemBJLUuhbGU4Y=
=PKfm
-----END PGP MESSAGE-----

**Comment by jgravois** [comment]
-----BEGIN PGP MESSAGE-----
Comment: GPGTools - https://gpgtools.org

hQIMA2DX8Pw201lnAQ/9G8lr8D7qXuVmGJp8apKIZlA5AaX/8CG2rfGkpVjrcxr7
hi5pjjzgb1mACfQbfJbpgAzFpDJqcGudkMfd3RdeT/HYvD/Za9O8QbYli6n9YfUa
QX9XNOBtxKPs3ksT2IXoTbqkut+HsFg3b0V2uqaCUlhSeCiuCGsmvDIjZBuWjBKt
D+XJDupXDvW+U3IdkyZcwjTHDzx92adCZWrKAA8syUe0uCRVckNCmKEHXszV8PLl
uUo1cEir5MmI6jatJvDbpCQC6jwLNNFcvHFJ5LrmWhPZ4DQoOdXjoQcYEh7JQ5L1
p7UIImrqsDZayNXIvLVZL4Qquar3FOCBJAqBEPwxwMQ8ZGJH18+dXvSC1wMeo9hv
aom5c/cRfi9z4i2tQpqtHtWR1AnldD8a9+E/tg9cixidXfd2bMtnx+r3kTwdQcvv
tY+1z54+gVAn6LqalmcMPcKCjPoJvp4txuo4LSxqD4iOE236G8CnJlqxWVOGhu/U
XuSqU9yxuL/S9sT31EhBes+vuN6kNV/v9tNM0BTxZLEAFaiVkMs3bnEzPzkIvA7V
XOmTKPiUROpIfKC44t/bh0LxbGboKiq4meNGbtz6ilGxGn1jWQLiyQwCTcXzkcjb
Etvm5BIHbS64YwSgGmsj11s5NZknLUPA4ZvLihjqn6G/o++ahkJ4GYFImeA2R6TS
6QHnLdF+826tKDgJUqTrH5+Z16KXysTCA8uZO931d8MGXARkaTa7WfhaoMv3Gv/V
T3eU29TZZSiIFG+JBUYgtapOBQ0hoGOZtSzLsu0Jiy4DF98OG3kQtxo//+5JqANx
WUYgnZksZXn7ZvtydSsdWB3mlHP6+su8kLdUKTy68BRYYc7Bvo+pl4yFXLSZA8kl
4QHh6uNlTaDZnIPdEg7wnaLya/aV7eRooPeVv3lnjkralOzS4edm0Vj8jxcegdQw
T5QyKyU/qLXjo/32biiayqm3aksD78ghYy/LUJ79OVOR5vVv4NJsu/oo8FHxgx3v
4BfkqesfQJlgaGQG+KP69Sa0RoPuFo8IxnBSypJ6Pi6/htFteYT8pUr5f0iNRh37
heeY7ErTs8DELGDVhcsfoTZ95vLrlAmRfLenBNoVVrcW602OVw3k+G/1o5UhsgPO
VPPwRDdGCe5rwXDXzL4OdiQbHaLAjBB2TNSi/Ha76ZOXL7tStIx31wOG5kUiaylw
a41aYJftfoyLnKOleJzn2bCYUAtZk4E3GYaFb97sYKlK7AUSyvf99ouyqoecGNTA
vgefiUv7VVVGzLjSBtAMO9j9UjoSBO8xmdCrhsENca78LeOaQ4z6QlrkGx0758LT
wl91Fw/hDrd4kkoe4cE5wDoix3ua7qrBjQfXuRrhdudTRDpdert3zicraw8/gkAQ
t7BMFg8lmCblPr0G6+yit7tvfdpqDjbZOFRW/wqqhkoJA/KAafn0AgikMuRIezGi
zDyGv/mp
=b5RW
-----END PGP MESSAGE-----

**Comment by ungoldman** [comment]
Can you encrypt emojis? I changed my username/domain and broke keybase, just wanted to say:

:wave:

**Comment by jgravois** [comment]
aom5c/cRfi9z4i2tQpqtHtWR1AnldD8a9+E/tg9cixidXfd2bMtnx+r3kTwdQcvv
tY+1z54+gVAn6LqalmcMPcKCjPoJvp4txuo4LSxqD4iOE236G8CnJlqxWVOGhu/U
XuSqU9yxuL/S9sT31EhBes+vuN6kNV/v9tNM0BTxZLEAFaiVkMs3bnEzPzkIvA7V
XOmTKPiUROpIfKC44t/bh0LxbGboKiq4meNGbtz6ilGxGn1jWQLiyQwCTcXzkcjb
Etvm5BIHbS64YwSgGmsj11s5NZknLUPA4ZvLihjqn6G/o++ahkJ4GYFImeA2R6TS

(thats encrypted for :two_men_holding_hands:)

**Comment by jgravois** [comment]
you game for more crypto email testing en route to writing an electron app?
1. first make sure you have GPG Suite installed.
2. import my updated [public key](https://dl.dropboxusercontent.com/u/59331579/B5FC_FA40_FA11_07BF.asc) into GPG Keychain
3. use “Mail” with the GPG extension and when you specify `jagravois@gmail.com` as the email address in the ‘To’ line, you’ll be able to click the lock button to encrypt a message for my eyes only (because i went the extra mile of [associating it](https://www.dropbox.com/s/00mb51zjfw080ob/Screenshot%202016-04-05%2015.41.56.png?dl=0)).

holler if any of that doesn't make sense.

--signed,
guy that now [signs his commits](https://github.com/jgravois/presentations/commit/153f06ea848a3624d871db7e4138cd8c813baaa5)

**Comment by ungoldman** [comment]
So verified. Very legit.

I just started a new contract job and I'm traveling to LA and Seattle in the next week, so I'm currently a bit swamped, but once I'm back and things settle down I would be most glad to get deeper into the crypto game.

**Comment by ungoldman** [comment]
@jgravois I am attempting to signal you on signal. I think the bug that affected my ability to access my account last spring has been fixed.

**Comment by jgravois** [comment]
🔐
