### ISSUE TITLE
openpdx

### ISSUE THREAD

**Issue by ungoldman** [ungoldman/contact#7]
@maxogden @fardog @bret when is a good time for us to get together and talk more about making [openpdx](http://openpdx.org/) a thing?

I talked with @fardog a bit over coffee last month and we agreed we wanted to keep it fairly low-maintenance and community event focused for now (at least in terms of our contributions). I said I'd be willing to do a monthly or twice-monthly sunday hack and chat like I used to do for @codeforportland, perhaps starting this month (November).

@maxogden mentioned some ideas on IRC (freenode/#opendx) as well:

```
Friday, October 16th, 2015
08:46:00 <ogd> ngoldman: for dat in the last couple weeks we got sponsored by some large cloud providers with free cloud hosting for open data
08:47:23 <ogd> ngoldman: so i'd be down to talk about how we can use that for openpdx projects. we are gonna write a sort of bittorrent tracker/dataset registry app for publishing open datasets but using p2p protocols to share them
14:48:12 <ogd> wut u think about adopting this model http://openprojectnight.org/seattle/
14:48:40 <ogd> (by sethvincent)
17:02:10 <ngoldman> sounds interesting
17:02:34 <ngoldman> i talked with seth a bit about the switch from code for seattle to open seattle
17:02:39 <ngoldman> we're motivated by similar issues
17:05:37 <ngoldman> you think we could host one at ctrl h?
17:06:35 <ngoldman> ogd: is that publicbits?
17:06:45 <ngoldman> (the tracker/dataset registry app)
19:50:14 <ogd> ngoldman: yep
Saturday, October 17th, 2015
17:34:02 <ogd> more inspiration http://hackerhours.org/diy-guide.html
Sunday, October 18th, 2015
15:48:20 <ogd> http://dcfemtech.github.io/tourdecode.html
```
- http://openprojectnight.org/seattle/
- http://hackerhours.org/diy-guide.html
- http://dcfemtech.github.io/tourdecode.html

I'd be interested in talking more and fleshing out some ideas in person. I'm pretty open all day Monday through Wednesday of this week. Please let me know if either of you have time!

**Comment by ungoldman** [comment]
Sorry meant @bcomnes not @bret.

**Comment by max-mapper** [comment]
i wanna do a waffle themed event. who wants to do waffle venue research? i got a tip that the waffle window on alberta would be a good winterproof waffle venue

**Comment by ungoldman** [comment]
winterproof waffling?... wise words. whatever works well.

**Comment by ungoldman** [comment]
Rudimentary research reveals these results:
- http://www.yelp.com/biz/the-waffle-window-portland
- http://www.yelp.com/biz/off-the-waffle-portland
- http://www.yelp.com/biz/smaaken-waffles-portland
- http://www.yelp.com/biz/pink-n-black-waffle-shack-portland
- http://www.yelp.com/biz/the-waffle-window-portland-2

**Comment by max-mapper** [comment]
@ngoldman nice, heres where i think we should visit in meatspace to taste the waffles and sample the ambiance:

waffle window (hawthorne): ![](http://s3-media2.fl.yelpcdn.com/bphoto/5h9bICw0nYTd1lZ1hXBdYQ/o.jpg)

waffle window 2 (alberta): ![](http://s3-media1.fl.yelpcdn.com/bphoto/1WTeY518Ssxj_Ym9WD2TWg/o.jpg)

off the waffle (clinton): ![](http://s3-media2.fl.yelpcdn.com/bphoto/M1xgI_XZNBWhPQ_6ivISxw/o.jpg)

**Comment by ungoldman** [comment]
would waffling wednesday work?

**Comment by max-mapper** [comment]
wednesday late afternoon should work for me

**Comment by ungoldman** [comment]
shall we say 3pm at the hawthorne waffle window? a little later/earlier works fine for me too.

**Comment by max-mapper** [comment]
i think i can do that yes

**Comment by bcomnes** [comment]
I dont get off till 4-5ish

**Comment by bcomnes** [comment]
Feel free to meet earlier. I can check in with yall later.

**Comment by ungoldman** [comment]
Alright I will aim to be there around 3. Fair warning: I have no phone right now, so unless I'm near wifi with my computer on I may be hard to reach. I'll try to stick around waffle window for a while.

**Comment by ungoldman** [comment]
Throwing @mannylopez into the mix as he expressed interest in getting involved too. :wave: 

I will try to get a regular study group cafe meetup going again in January.

@maxogden how did the node study group go? let me know if you want to do waffle.js or curryrice.js in the future.

@fardog hi! @bcomnes hello! I haven't done much more with this idea since we last talked. still interested, just working on moving to a new place and working this month.

**Comment by fardog** [comment]
> curryrice.js

:D

**Comment by ungoldman** [comment]
So I kind of blew it on making this into a thing but http://donutjs.club is a thing and @bcomnes and @fardog are doing a lot of the work (all?) for pdxnode, maybe yet another meetup group is not needed right now. I still like @maxogden's idea about focusing on workshops and working with ctrl^h, maybe I'll give it a go again later this year. Thanks all for chatting about it.
