### ISSUE TITLE
Paul C Pederson in the <head>

### ISSUE THREAD

**Issue by mbcharbonneau** [ungoldman/contact#8]
Probably the xml feed link title isn't supposed to include any Pederson?

![screen shot 2016-03-11 at 10 19 15 am](https://cloud.githubusercontent.com/assets/4793/13711321/bea08d54-e772-11e5-845e-6cb4766d055c.png)

**Comment by ungoldman** [comment]
hehehehe

**Comment by ungoldman** [comment]
Hi @paulcpederson, I did a search and replace on your site and published it as my own but I missed a spot.

**Comment by ungoldman** [comment]
Fixed! Now http://ungoldman.com/feed.xml actually exists too. Thanks for finding that @mbcharbonneau.
