### ISSUE TITLE
Horse with Hands

### ISSUE THREAD

**Issue by ungoldman** [ungoldman/contact#9]
> cc @courtf @paulcpederson
- [ ] Barbershop
- [ ] Streets of rage
- [ ] Sandwich artist - food prep
- [ ] Drummer recital - guitar hero
- [ ] Symphony conductor
- [ ] First day of school
- [ ] Tennis
- [ ] Fencing
- [ ] Basketball
- [ ] Bowling
- [ ] Assembly line
- [ ] Putting out a fire
- [ ] Something with buckets
- [ ] Weightlifting - gym style
- [ ] Fine dining - diner or waiter

**Comment by ungoldman** [comment]
Still a solid idea guys

**Comment by paulcpederson** [comment]
> Something with buckets

**Comment by ungoldman** [comment]
Perchance to dream...
